// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9fyWHtMuGv9fyOCYi_ytkJSBftlJj_A',
    appId: '1:76147858957:web:63285b9ee2a4b8e218ff44',
    messagingSenderId: '76147858957',
    projectId: 'digital-manu-fce86',
    authDomain: 'digital-manu-fce86.firebaseapp.com',
    storageBucket: 'digital-manu-fce86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvYPxtwYLB191YP8EGYgxH_CipEU7WwvM',
    appId: '1:76147858957:android:10104bf96b7fd9ea18ff44',
    messagingSenderId: '76147858957',
    projectId: 'digital-manu-fce86',
    storageBucket: 'digital-manu-fce86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCftv9SNMYVrKFnP7dE0o2znVTD-dF3T3Q',
    appId: '1:76147858957:ios:b82a75dd288b42c418ff44',
    messagingSenderId: '76147858957',
    projectId: 'digital-manu-fce86',
    storageBucket: 'digital-manu-fce86.firebasestorage.app',
    iosBundleId: 'com.example.digitalManu',
  );
}
